"""Minimal type stub for msgpack (no upstream stubs available)."""

from collections.abc import Callable

class Packer:
    def __init__(
        self,
        *,
        use_bin_type: bool = ...,
        autoreset: bool = ...,
        datetime: bool = ...,
    ) -> None: ...
    def reset(self) -> None: ...
    def pack(self, obj: object) -> None: ...
    def getbuffer(self) -> memoryview: ...
    def packb(self, obj: object) -> bytes: ...

class Unpacker:
    def __init__(
        self,
        *,
        raw: bool = ...,
        use_bin_type: bool = ...,
        max_buffer_size: int = ...,
    ) -> None: ...
    def feed(self, data: bytes | bytearray | memoryview) -> None: ...
    def unpack(self) -> object: ...
    def __next__(self) -> object: ...
    def __iter__(self) -> Unpacker: ...

def packb(obj: object, *, use_bin_type: bool = ...) -> bytes: ...
def unpackb(
    data: bytes | bytearray | memoryview,
    *,
    raw: bool = ...,
    use_bin_type: bool = ...,
    strict_map_key: bool = ...,
) -> object: ...
def pack(obj: object, default: Callable[[object], object] | None = ...) -> bytes: ...
def unpack(
    data: bytes | bytearray | memoryview,
    default: Callable[[object], object] | None = ...,
) -> object: ...
